Allow specify user context in GitHub Status window
sclorg/tfaga-wrapper pull request #14
Opened 2023-11-28 12:10 UTC by phracek

Allow specify user context in GitHub Status window

    The context after this modification looks like:
    In case of context is not specified, then status is:
    `Testing Farm - <OS> - <version>`

    In case of context is specified, then status is:
    `Testing Farm - <context> <OS> - <version>`

2023-11-28 12:56 UTC, jamacku commented on export_variables.sh
> +$context_prefix=""
@phracek, you probably don't want the value of `context_prefix`. Just remove `$`

2023-11-28 12:56 UTC, jamacku commented on export_variables.sh
> +  $context_prefix="$user_context - "
The same here.

2024-05-21 10:35 UTC, phracek commented
@jamacku Thanks for review. Can you please have a look at it once more?

2024-05-21 10:52 UTC, jamacku requested changes

2024-05-21 10:52 UTC, jamacku commented on export_variables.sh
> +  context_prefix="$user_context -"
I would prefer this:

```sh
if [[ -n "$user_context" ]]; then
  context_prefix="$user_context - "
fi
```

And then you can drop the above if condition.

2024-05-21 10:52 UTC, jamacku commented on export_variables.sh
> +user_context="$3"
Maybe also add a comment.

2024-05-21 10:52 UTC, jamacku commented on action.yml
> +          echo "ctx=undefined >> "$GITHUB_OUTPUT"
I think you can pass `inputs.context` directly.

2024-05-21 10:57 UTC, zmiklank commented
@phracek, could you please share why we need this feature? What will be specified in the <context>?

2024-05-21 11:37 UTC, jamacku approved these changes
LGTM

2024-05-21 11:45 UTC, merged